version: '3.9'

services:
  mysqldb:
    container_name: myapp-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lealtad
      MYSQL_USER: trabajo
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  rest-api:
    build:
      context: .
    container_name: lealtad-app
    volumes:
      - .:/app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

